apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-book-service
spec:
  selector:
    matchLabels:
      app: elastic-book-service
  replicas: 1
  template:
    metadata:
      labels:
        app: elastic-book-service
    spec:
      containers:
        - name: elastic-book-service
          image: pasapples/elastic-book-service:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
          - name: ELASTIC_APM_SERVER_URLS
            valueFrom:
              configMapKeyRef:
                name: apm-agent-details
                key: server_urls
          - name: ELASTIC_APM_SERVICE_NAME
            valueFrom:
              configMapKeyRef:
                name: apm-agent-details
                key: service_name
          - name: ELASTIC_APM_APPLICATION_PACKAGES
            valueFrom:
              configMapKeyRef:
                name: apm-agent-details
                key: application_packages
          - name: ELASTIC_APM_SECRET_TOKEN
            valueFrom:
              secretKeyRef:
                name: apm-token-secret
                key: secret_token

---
apiVersion: v1
kind: Service
metadata:
  name: elastic-book-service-lb
  labels:
    name: elastic-book-service-lb
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: elastic-book-service
  type: LoadBalancer